export const CLIENTS_LOADING = "CLIENTS_LOADING";
export const CLIENTS_LOADING_SUCCESS = "CLIENTS_LOADING_SUCCESS";
export const CLIENTS_LOADING_ERROR = "CLIENTS_LOADING_ERROR";
export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT";
export const UPDATE_SELECTED_CLIENT = "UPDATE_SELECTED_CLIENT";
